-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unexpected token after '-user start hyprland-session.target'
local browser = "firefox"
local color0 = "rgba(7,16,31,1.0)"
local color14 = "rgba(212,154,156,1.0)"
local color3 = "rgba(204,61,82,1.0)"
local filemanager = "nemo ~/Dropbox"
local menu = "rofi -show drun"
local messenger = "signal-desktop"
local music = "amarok"
local passwordManager = "bitwarden"
local random_wall = "~/.dotfiles/home/features/hyprland/scripts/wall-random.sh"
local terminal = "kitty"
-- Source: ~/.cache/wal/colors-hyprland.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("colors-hyprland")
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + space", hl.dsp.exec_cmd(menu))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + E", hl.dsp.exec_cmd(filemanager))
hl.bind("SUPER + B", hl.dsp.exec_cmd(browser))
hl.bind("SUPER + W", hl.dsp.exec_cmd("wall-random"))
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("waybar-reload"))
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("flameshot gui"))
hl.bind("SUPER + ESCAPE", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + SHIFT + ESCAPE", hl.dsp.exit())
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "", action = "toggle" }))
hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind("SUPER + comma", hl.dsp.focus({ workspace = -1 }))
hl.bind("SUPER + period", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind("SUPER + SHIFT + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind("SUPER + SHIFT + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind("SUPER + SHIFT + down", hl.dsp.window.swap({ direction = "d" }))
hl.bind("SUPER + minus", hl.dsp.window.resize({ x = -100, y = 0, relative = true }))
hl.bind("SUPER + equal", hl.dsp.window.resize({ x = 100, y = 0, relative = true }))
hl.bind("SUPER + SHIFT + minus", hl.dsp.window.resize({ x = 0, y = -100, relative = true }))
hl.bind("SUPER + SHIFT + equal", hl.dsp.window.resize({ x = 0, y = 100, relative = true }))
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

hl.env("GDK_SCALE", "2")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("HYPRCURSOR_THEME", "Adwaita")
-- TODO: manual review — malformed env on line 137: GDK_BACKEND,wayland,x11,*
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("CHROMIUM_FLAGS", "\"--enable-features=UseOzonePlatform --ozone-platform=wayland --gtk-version=4\"")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("MOZ_WEBRENDER", "1")
hl.env("MOZ_ACCELERATED", "1")
hl.env("XDG_MENU_PREFIX", "plasma-")
hl.env("XDG_DATA_DIRS", "$XDG_DATA_DIRS:$HOME/.nix-profile/share:/nix/var/nix/profiles/default/share")
hl.env("GTK_THEME", "Adwaita:dark")

hl.layer_rule({
    match = { namespace = "match:namespace wofi" },
    -- TODO: manual review — unmapped layer rule: "blur on"
    animation = "off",
})

hl.layer_rule({
    match = { namespace = "match:namespace ^(wofi)$" },
    ignore_alpha = 0.5,
})

hl.layer_rule({
    match = { namespace = "match:namespace waybar" },
    -- TODO: manual review — unmapped layer rule: "blur on"
})

hl.monitor({
    output = "DP-1",
    mode = "3840x2160",
    position = "0x0",
    scale = "1.5",
})

hl.monitor({
    output = "DP-2",
    mode = "3840x2160",
    position = "2560x0",
    scale = "1.5",
})

hl.window_rule({
    match = {
        class = "^(Zotero)$",
        title = ".*Preferences*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(Zotero)$",
        title = ".*Citation*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = true,
})

hl.window_rule({
    match = {
        class = "^(org.kde.kcalc)$",
    },
    float = true,
    size = "400 400",
    focus_on_activate = true,
    move = "onscreen cursor -200 -200",
})

hl.window_rule({
    match = {
        class = "^(mpv)$",
    },
    content = "none",
})

hl.window_rule({
    match = {
        class = "^(xwaylandvideobridge)$",
    },
    opacity = "0.0 override",
    no_anim = true,
    no_initial_focus = true,
    max_size = "1 1",
    no_blur = true,
    no_focus = true,
})

hl.window_rule({
    match = {
        title = "^(flameshot)$",
    },
    float = true,
    move = "0 0",
    suppress_event = "fullscreen",
    pin = true,
    fullscreen_state = "0 0",
})

hl.window_rule({
    match = {
        class = "^(wofi)$",
    },
    animation = "off",
})

hl.workspace_rule({
    workspace = "1",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "2",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "3",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "4",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "5",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "6",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "7",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "8",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = "9",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = "10",
    -- TODO: manual review — workspace field "persistent"
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = "1",
    default = true,
    monitor = "DP-1",
})

hl.workspace_rule({
    workspace = "8",
    default = true,
    monitor = "DP-2",
})

hl.config({
    animations = {
        enabled = false,
    },
    decoration = {
        blur = {
            enabled = true,
            passes = 2,
            size = 3,
            vibrancy = 0.169600,
        },
        shadow = {
            color = "rgba(1a1a1aee)",
            enabled = true,
            range = 4,
            render_power = 3,
        },
        active_opacity = 1,
        inactive_opacity = 1,
        rounding = 10,
        rounding_power = 2,
    },
    dwindle = {
        force_split = 0,
        preserve_split = true,
    },
    general = {
        allow_tearing = false,
        border_size = 2,
        col = {
            active_border = color14 .. " " .. color3 .. " 45deg",
            inactive_border = color0,
        },
        gaps_in = 4,
        gaps_out = 8,
        layout = "dwindle",
        resize_on_border = true,
    },
    input = {
        touchpad = {
            clickfinger_behavior = true,
            disable_while_typing = true,
            natural_scroll = true,
        },
        follow_mouse = 1,
        kb_layout = "dk",
        sensitivity = 0,
    },
    master = {
        new_status = "master",
    },
    misc = {
        anr_missed_pings = 30,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("/nix/store/ai8mmqghspvnhv2jz12pfg6b6dqmg3b3-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl -")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORM QT_AUTO_SCREEN_SCALE_FACTOR QT_WAYLAND_DISABLE_WINDOWDECORATION")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("/nix/store/nd27p0cy4apna3javhv9v5ixgryy2089-kwallet-pam-6.6.5/libexec/pam_kwallet_init")
    hl.exec_cmd("kwallet-query -l kdewallet &> /dev/null")
    hl.exec_cmd("maestral start &> /dev/null")
    hl.exec_cmd("wl-clip-persist --clipboard regular & clipse -listen")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("swaync")
    hl.exec_cmd("swaync-client -df")
    hl.exec_cmd("sleep 1 && " .. random_wall .. " &> /dev/null")
    hl.exec_cmd("remmina -i")
    hl.exec_cmd("maestral_qt")
    hl.exec_cmd("waybar-reload")
    hl.exec_cmd("wall-random")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("pkill -SIGUSR2 waybar || waybar")
end)

