# =====================================================================
# MangoWM Global Application & Script Variables (config.conf)
# =====================================================================

# Default Applications (Registered as custom config variables)
set$terminal=kitty
set$filemanager=nemo ~/Dropbox
set$browser=firefox
set$menu=rofi -show drun
set$music=amarok
set$passwordManager=bitwarden
set$messenger=signal-desktop


# keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=dk

# Touchpad
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
mouse_natural_scrolling=1
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1
mouse_accel_profile=2
mouse_accel_speed=0.0
scroll_method=1 # 1 = two-finger, 2 = edge, 4 = button
click_method=2 # 1 = button areas, 2 = clickfinger

# Mouse
mouse_natural_scrolling=0
mouse_accel_profile=0	      #0 (None), 1 (Flat), 2 (Adaptive).
mouse_accel_speed=0.0	# Speed adjustment (-1.0 to 1.0).
left_handed=0	# Swap left and right buttons.
axis_scroll_factor=1.0	# Scroll factor for axis scroll speed (0.1–10.0).

follow_mouse=1
warp_cursor_to_focus=0



# Leftover from env
# Tell the compositor core itself to match the system cursor layouts
env=XCURSOR_SIZE,24
env=XCURSOR_THEME,Adwaita

# Force zero scaling on XWayland to keep old apps looking sharp (unscaled)
xwayland_force_zero_scaling=1
