# ==================================================
# MangoWM Monitor Rules for Host: taupa
# ==================================================

# Shifted Y by +560px to completely avoid negative XWayland coordinates
# DP-2: Main display shifted down
monitorrule=name:^DP-2$,width:3840,height:2160,x:0,y:560,scale:1.5

# DP-4: Side display at top-right, rotated 90° counter-clockwise (rr:1)
monitorrule=name:^DP-4$,width:3840,height:2160,x:2560,y:0,scale:1.5,rr:1

# Binding Persistent Tags 1-7 to DP-2
tagrule=tag:1,monitor:DP-2,layout:dwindle
tagrule=tag:2,monitor:DP-2,layout:dwindle
tagrule=tag:3,monitor:DP-2,layout:dwindle
tagrule=tag:4,monitor:DP-2,layout:dwindle
tagrule=tag:5,monitor:DP-2,layout:dwindle
tagrule=tag:6,monitor:DP-2,layout:dwindle


# Binding Persistent Tags 8-10 to DP-4
tagrule=tag:7,monitor:DP-4,layout:vertical_tile
tagrule=tag:8,monitor:DP-4,layout:vertical_tile
tagrule=tag:9,monitor:DP-4,layout:vertical_tile
