# ==================================================
# MangoWM Monitor Rules for Host: taude
# ==================================================

# Shifted Y by +560px to completely avoid negative XWayland coordinates
# DP-2: Main display shifted down
monitorrule=name:^DP-1$,width:3840,height:2160,x:0,y:560,scale:1.5

# DP-4: Side display at top-right
monitorrule=name:^DP-2$,width:3840,height:2160,x:2560,y:0,scale:1.5

# Binding Persistent Tags 1-7 to DP-1
tagrule=id:1,monitor_name:DP-1,layout_name:dwindle
tagrule=id:2,monitor_name:DP-1,layout_name:dwindle
tagrule=id:3,monitor_name:DP-1,layout_name:dwindle
tagrule=id:4,monitor_name:DP-1,layout_name:dwindle
tagrule=id:5,monitor_name:DP-1,layout_name:dwindle
tagrule=id:6,monitor_name:DP-1,layout_name:dwindle


# Binding Persistent Tags 8-10 to DP-2
tagrule=id:7,monitor_name:DP-2,layout_name:dwindle
tagrule=id:8,monitor_name:DP-2,layout_name:dwindle
tagrule=id:9,monitor_name:DP-2,layout_name:dwindle

