# ==================================================
# MangoWM Monitor Rules: Default Fallback
# ==================================================

# Catch-all matching rule if no hostname parameters trigger
monitorrule=name:.*,x:0,y:0
