# =====================================================================
# Default MangoWM Pywal Colors 
# =====================================================================

# Color definitions (Converted from rgba to 0xffRRGGBB Hex Vectors)
# based on wallpaper: /home/ohm/.dotfiles/wallpapers/egor-komarov-w1wUjj5FonI-unsplash.jpg
set$wallpaper=/home/ohm/.dotfiles/wallpapers/egor-komarov-w1wUjj5FonI-unsplash.jpg
set$foreground=0xffc1c2c4
set$background=0xff080b13

set$color0=0xff080b13
set$color1=0xff332a6a
set$color2=0xff4d296d
set$color3=0xff5c368a
set$color4=0xff334487
set$color5=0xff674a9d
set$color6=0xffaa5f86
set$color7=0xff8c9096
set$color8=0xff575d6b
set$color9=0xff5547a6
set$color10=0xff7a47a7
set$color11=0xff8257b7
set$color12=0xff5467b6
set$color13=0xff896cc0
set$color14=0xffc77ea4
set$color15=0xffc1c2c4
