# =====================================================================
# Default MangoWM Pywal Colors 
# =====================================================================

# Color definitions (Converted from rgba to 0xffRRGGBB Hex Vectors)
# based on wallpaper: /home/ohm/.dotfiles/wallpapers/egor-komarov-w1wUjj5FonI-unsplash.jpg
# wallpaper=/home/ohm/.dotfiles/wallpapers/egor-komarov-w1wUjj5FonI-unsplash.jpg
#foreground=0xffc1c2c4
#background=0xff080b13

#color0=0xff080b13
#color1=0xff332a6a
#color2=0xff4d296d
#color3=0xff5c368a
#color4=0xff334487
#color5=0xff674a9d
#color6=0xffaa5f86
#color7=0xff8c9096
#color8=0xff575d6b
#color9=0xff5547a6
#color10=0xff7a47a7
#color11=0xff8257b7
#color12=0xff5467b6
#color13=0xff896cc0
#color14=0xffc77ea4
#color15=0xffc1c2c4
