# Mango main theme

# Focus Color (Using your accent accent color14)
#focuscolor = $color14

# Border Color (Using your background color0)
#bordercolor = $color0

# Window Layout Options
#gaps_in = 4
#gaps_out = 8
#border_size = 2
#resize_on_border = 1
#rounding = 10
#active_opacity = 1.0
#inactive_opacity = 1.0
#blur_enabled = 1
#blur_size = 3
#blur_passes = 2
#animations_enabled = 0
